version: '3'

services:
  #servicio de mysql
  mysql: 
    image: mysql:8.0
    container_name: mi_mysql 
    environment:
       MYSQL_ROOT_PASSWORD: 1234
    volumes:
       - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

volumes:
 mysql-data:

networks:
 my_network: